version: '3.4'

services:
  mongodb:
    image: mongo:4.4.18
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    env_file:
      - .env
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  flask_app:
    build: .
    restart: always
    ports:
      - "5001:5000"
    environment:
      MONGO_URI: mongodb://${MONGO_ROOT_USER}:${MONGO_ROOT_PASSWORD}@mongodb:27017/
    volumes:
      - ./config:/app/config
      - ./app:/app/app # uncomment to enable on-the-fly changes
    depends_on:
      - mongodb

volumes:
  mongo-data:
