version: '3.4'

services:
  flask_app:
    build: .
    restart: always
    ports:
      - "5001:5000"
    environment:
      MONGO_URI: mongodb://${MONGO_ROOT_USER}:${MONGO_ROOT_PASSWORD}@${MONGO_HOST}:27017/
    volumes:
      - ./config:/app/config
      - ./app:/app/app # uncomment to enable on-the-fly changes
